import { applyMiddleware, createStore } from 'redux';
import { createLogger } from 'redux-logger';
import thunk from 'redux-thunk';
import reducer from './reducers/index';

export const configureStore = () => {
  // Promise middlware
  const middlewares = [thunk];

  // Conditionally apply logging middlware when not in production
  if (process.env.NODE_ENV !== 'production' && typeof window !== 'undefined') {
    // Logs all the actions except the ones generated by redux-from
    middlewares.push(createLogger({
      predicate: (getState, action) => !action.type.includes('redux-form'),
      collapsed: true
    }));
  }


  // Create store
  return createStore(
    reducer,
    applyMiddleware(...middlewares)
  );
};
