export const DISPLAY_MESSAGE = 'DISPLAY_MESSAGE';

export const FETCH_AGENTS_REQUEST = 'FETCH_AGENTS_REQUEST ';
export const FETCH_AGENTS_SUCCESS = 'FETCH_AGENTS_SUCCESS';
export const FETCH_AGENTS_ERROR = 'FETCH_AGENTS_ERROR';

export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST ';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';